"""Add Review Model

Revision ID: 0541bbfd583a
Revises: 08e310ce1b48
Create Date: 2024-01-02 13:05:26.199019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0541bbfd583a'
down_revision = '08e310ce1b48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
